# Generated by Django 3.0.4 on 2020-03-31 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_studyrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='class_teacher',
            field=models.ForeignKey(limit_choices_to={'depart__title': '教质部'}, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='web.UserInfo', verbose_name='班主任'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Course', verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.School', verbose_name='校区'),
        ),
        migrations.AlterField(
            model_name='classlist',
            name='tech_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'depart__title__in': ['Linux教学部', 'Python教学部']}, related_name='teach_classes', to='web.UserInfo', verbose_name='任课老师'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.UserInfo', verbose_name='跟踪人'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Customer', verbose_name='所咨询客户'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='class_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.ClassList', verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='courserecord',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.UserInfo', verbose_name='讲师'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='consultant',
            field=models.ForeignKey(blank=True, limit_choices_to={'depart__title': '销售部'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultant', to='web.UserInfo', verbose_name='课程顾问'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='referral_from',
            field=models.ForeignKey(blank=True, help_text='若此客户是转介绍自内部学员,请在此处选择内部学员姓名', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='internal_referral', to='web.Customer', verbose_name='转介绍自学员'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='class_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.ClassList', verbose_name='申请班级'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='confirm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirms', to='web.UserInfo', verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='consultant',
            field=models.ForeignKey(help_text='谁签的单就选谁', on_delete=django.db.models.deletion.PROTECT, to='web.UserInfo', verbose_name='课程顾问'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Customer', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.UserInfo', verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='student',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='web.Customer', verbose_name='客户信息'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='course_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.CourseRecord', verbose_name='第几天课程'),
        ),
        migrations.AlterField(
            model_name='studyrecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Student', verbose_name='学员'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Department', verbose_name='部门'),
        ),
    ]
